# Generated by Django 5.0.2 on 2026-06-25 12:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0014_employee_salary_payroll'),
        ('expenses', '0001_system_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra pay for this month (commission, bonus, etc.).', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially paid'), ('SETTLED', 'Settled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_entries', to='accounts_core.employee')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.employeesalaryentry')),
                ('operating_expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payment', to='expenses.operatingexpense')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-posted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeesalaryentry',
            constraint=models.UniqueConstraint(fields=('employee', 'period_year', 'period_month'), name='uniq_employee_salary_period'),
        ),
    ]
