# Generated by Django 5.0.6 on 2024-08-26 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user', 'Travel date reminder'), ('invoice', 'Follow-up reminder'), ('task', 'Payment Due Date'), ('followup', 'Supplier Payment')], default='user', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('when', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
