# Generated by Django 5.0.6 on 2025-01-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user', 'Travel date reminder'), ('invoice', 'Follow-up reminder'), ('task', 'Payment Due Date'), ('followup', 'Supplier Payment'), ('anniversary', 'Birthday Anniversary')], default='user', max_length=50),
        ),
    ]
