# Generated by Django 5.0.2 on 2026-06-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event_service'),
        ('display', '0010_user_crm_roles'),
        ('tasks', '0007_crm_invoice_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_events', to='display.lead'),
        ),
        migrations.AddField(
            model_name='event',
            name='leadtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='tasks.leadtask'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='tasks.payment'),
        ),
    ]
