# Generated by Django 5.0.2 on 2026-06-24 00:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_core', '0012_userprofile_is_accountant'),
        ('catalog', '0003_servicefielddefinition_field_type_default'),
        ('display', '0010_user_crm_roles'),
        ('sales', '0014_initial'),
        ('tasks', '0009_seed_client_pdf_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_sync_from', models.DateField(default=django.utils.timezone.localdate, help_text='CRM invoices saved on or after this date are queued for accountant review.')),
                ('master_data_sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounting integration settings',
            },
        ),
        migrations.CreateModel(
            name='CrmDestinationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200, unique=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('acc_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_links', to='catalog.destination')),
            ],
        ),
        migrations.CreateModel(
            name='CrmEmployeeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_user_link', to='accounts_core.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_employee_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrmServiceTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('acc_service_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_service_type_link', to='catalog.servicetype')),
                ('crm_service_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_link', to='tasks.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='CrmSupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('acc_supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_supplier_link', to='accounts_core.supplier')),
                ('crm_supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_link', to='tasks.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved (draft in accounting)'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published in accounting'), ('SKIPPED', 'Skipped')], default='PENDING_REVIEW', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_crm_snapshot_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leadtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_sync', to='tasks.leadtask')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoice_syncs', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sync_queue', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'CRM invoice sync queue',
                'verbose_name_plural': 'CRM invoice sync queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_key', models.CharField(db_index=True, help_text='Normalized phone digits for matching.', max_length=32)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_lead_link', to='accounts_core.client')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_client_link', to='display.lead')),
            ],
            options={
                'verbose_name': 'Lead → client link',
            },
        ),
        migrations.CreateModel(
            name='PartyOpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('CLIENT', 'Client'), ('SUPPLIER', 'Supplier')], max_length=10)),
                ('as_of_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='accounts_core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='accounts_core.supplier')),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
    ]
