"""Jazzmin admin theme configuration.

Kept in its own module so both the dev settings (``system/settings.py``) and the
production settings (``ghaithleads/settings.py``, which the deploy script keeps
separate) can share one source of truth via ``from .jazzmin_config import *``.
"""

JAZZMIN_SETTINGS = {
    "site_title": "Ghaith Admin",
    "site_header": "Ghaith Travel",
    "site_brand": "Ghaith Admin",
    "site_logo": None,
    "welcome_sign": "Ghaith Travel administration",
    "copyright": "Ghaith Travel",
    "search_model": ["display.Lead", "auth.User", "tasks.LeadTask"],
    "topmenu_links": [
        {"name": "CRM", "url": "/", "new_window": False},
        {"name": "Orders", "url": "/tasks/leads/current/", "new_window": False},
        {"name": "Sophia sync", "url": "/api/whatsapp/sync/now/", "new_window": False},
        {"model": "display.Lead"},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": ["api", "reporting"],
    "hide_models": [
        "tasks.task",
        "tasks.tag",
        "sales.salesinvoiceline",
        "purchases.supplierbillline",
        "catalog.servicefielddefinition",
        "accounts_core.userprofile",
        "accounts_core.documentsequence",
        "notifications.pushsubscription",
        "accounting_bridge.crmsupplierlink",
        "accounting_bridge.crmdestinationlink",
        "accounting_bridge.crmservicetypelink",
        "accounting_bridge.crmemployeelink",
        "treasury.arallocation",
        "treasury.apallocation",
    ],
    "order_with_respect_to": [
        "display",
        "tasks",
        "catalog",
        "dashboard",
        "notifications",
        "auth",
        "accounts_core",
        "sales",
        "purchases",
        "treasury",
        "expenses",
        "accounting_bridge",
        "auditlog",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "display": "fas fa-headset",
        "display.Lead": "fas fa-user-tag",
        "display.Department": "fas fa-sitemap",
        "display.Destination": "fas fa-map-marker-alt",
        "display.Offer": "fas fa-file-invoice",
        "display.DailyReport": "fas fa-clipboard-list",
        "display.MonthlyTarget": "fas fa-bullseye",
        "display.UserMonthlyTarget": "fas fa-chart-line",
        "display.SophiaSyncState": "fab fa-whatsapp",
        "tasks": "fas fa-clipboard-check",
        "tasks.LeadTask": "fas fa-suitcase",
        "tasks.Service": "fas fa-concierge-bell",
        "tasks.Supplier": "fas fa-truck",
        "tasks.ServiceType": "fas fa-list",
        "tasks.PdfPolicy": "fas fa-file-alt",
        "tasks.ClientMediaUploadLink": "fas fa-photo-video",
        "tasks.BabylonHotelEntry": "fas fa-hotel",
        "catalog": "fas fa-book",
        "catalog.Destination": "fas fa-globe",
        "catalog.ServiceType": "fas fa-tags",
        "dashboard": "fas fa-calendar-alt",
        "dashboard.Event": "fas fa-calendar",
        "notifications": "fas fa-bell",
        "notifications.UserNotification": "fas fa-bell",
        "notifications.ChatMessage": "fas fa-comments",
        "accounts_core": "fas fa-address-book",
        "accounts_core.Client": "fas fa-user-tie",
        "accounts_core.Supplier": "fas fa-industry",
        "accounts_core.Employee": "fas fa-id-badge",
        "accounts_core.CompanyBranding": "fas fa-building",
        "accounts_core.Currency": "fas fa-coins",
        "sales": "fas fa-file-invoice-dollar",
        "sales.SalesInvoice": "fas fa-file-invoice-dollar",
        "sales.CreditNote": "fas fa-undo",
        "purchases": "fas fa-shopping-cart",
        "purchases.SupplierBill": "fas fa-file-invoice",
        "purchases.ExpenseCategory": "fas fa-folder-open",
        "treasury": "fas fa-university",
        "treasury.Payment": "fas fa-money-check-alt",
        "treasury.MoneyAccount": "fas fa-wallet",
        "expenses": "fas fa-receipt",
        "accounting_bridge": "fas fa-link",
        "auditlog": "fas fa-history",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "display.lead": "horizontal_tabs",
        "tasks.leadtask": "horizontal_tabs",
    },
    "custom_links": {
        "display": [
            {"name": "Open CRM", "url": "/", "icon": "fas fa-home", "permissions": ["display.view_lead"]},
            {
                "name": "Run Sophia sync",
                "url": "/api/whatsapp/sync/now/",
                "icon": "fab fa-whatsapp",
                "permissions": ["display.view_lead"],
            },
        ],
        "tasks": [
            {"name": "All orders", "url": "/tasks/leads/current/", "icon": "fas fa-list", "permissions": ["tasks.view_leadtask"]},
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-navy",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}
