"""
Django settings for system project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# there is a lot of configs in django , go and learn them 
# one by one to get the maximum out of the system

# TODO: do some testing to find the best caching 
# mechanism for this project , most of the problems 
# that i still did not get right are caused by caching
# or the dummy caching mechanism has some part in

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_REDIRECT_URL = '/'
# NOTE: they say here that this is unsuitable for production

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# what makes the secret key , how to generate it and what does 
# the creation of this key looks like and what should i put in here
# plus consider to put the secret key in the settings file that 
# is on the server

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%a3!s$=qh*z3#cjxbq^8exok0yd8vk=my($8=hjtc*@$8c&5c6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# here the new domain refers to nothing
ALLOWED_HOSTS = ['thenewdomain.domain', 'localhost']

# settings.py


# Application definition

# NOTE : i think that there should be a caching app in here
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'display',
    'tasks',
    'dashboard',
    'notifications',
    'accounts_core.apps.AccountsCoreConfig',
    'catalog',
    'sales',
    'purchases',
    'treasury',
    'expenses',
    'reporting',
    'auditlog',
    'api',
    'accounting_bridge.apps.AccountingBridgeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounting_bridge.middleware.AccountingAccessMiddleware',
    'reporting.middleware.ReportDateDefaultsMiddleware',
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ghaith_accounting' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts_core.context_processors.pdf_branding',
                'accounting_bridge.context_processors.app_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# TODO : here i am using a databse like this just for development, for publish use the database that is in the connected server
# NOTE : the previous published version of this code include the 
# settings for the database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Beirut'

# are those needed
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / 'static_root/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
if 'test' in os.sys.argv:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Browser push (Web Push / VAPID). Generate with: python manage.py generate_vapid_keys --write
def _load_vapid_env():
    vapid_file = BASE_DIR / 'deploy' / 'vapid.env'
    if not vapid_file.exists():
        return
    for line in vapid_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key.strip(), value)


_load_vapid_env()
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:admin@ghaithtravel.com')

# Full site URL for browser push icons (production: https://ghaithtravel.pythonanywhere.com)
CRM_SITE_URL = os.environ.get('CRM_SITE_URL', 'http://127.0.0.1:8000')
CRM_PUSH_ICON_URL = '/static/img/favicon.svg'

# Embedded accounting module (Ghaith branding — no Sama references)
COMPANY_LEGAL_NAME = os.environ.get('COMPANY_LEGAL_NAME', 'Ghaith Travel')
COMPANY_ADDRESS = os.environ.get('COMPANY_ADDRESS', 'Bechara El Khoury Highway, Beirut, Lebanon')
COMPANY_PHONE = os.environ.get('COMPANY_PHONE', '+961-81456406')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'info@ghaithtravel.com')
COMPANY_FINANCIAL_ACCOUNT = os.environ.get('COMPANY_FINANCIAL_ACCOUNT', '')
COMPANY_FOOTER_TEXT = os.environ.get('COMPANY_FOOTER_TEXT', '© Ghaith Travel. All rights reserved.')
COMPANY_TAGLINE = os.environ.get('COMPANY_TAGLINE', 'Ghaith Travel & Tourism')
COMPANY_DEFAULT_CURRENCY = os.environ.get('COMPANY_DEFAULT_CURRENCY', 'USD')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
