"""
Django settings for system project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# there is a lot of configs in django , go and learn them 
# one by one to get the maximum out of the system

# TODO: do some testing to find the best caching 
# mechanism for this project , most of the problems 
# that i still did not get right are caused by caching
# or the dummy caching mechanism has some part in

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
# NOTE: they say here that this is unsuitable for production

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# what makes the secret key , how to generate it and what does 
# the creation of this key looks like and what should i put in here
# plus consider to put the secret key in the settings file that 
# is on the server

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%a3!s$=qh*z3#cjxbq^8exok0yd8vk=my($8=hjtc*@$8c&5c6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Local + production + tunnels (ngrok / Cloudflare) so Sophia/WhatsApp can hit this server.
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    '0.0.0.0',
    'thenewdomain.domain',
    'ghaithtravel.pythonanywhere.com',
    'www.ghaithtravel.pythonanywhere.com',
    '.ngrok-free.app',
    '.ngrok.io',
    '.ngrok.app',
    '.trycloudflare.com',
    '.loca.lt',
]
# DEBUG local testing: accept any Host (needed for changing tunnel URLs).
if DEBUG:
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://ghaithtravel.pythonanywhere.com',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.ngrok.app',
    'https://*.trycloudflare.com',
]

# settings.py


# Application definition

# NOTE : i think that there should be a caching app in here
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'display',
    'tasks',
    'dashboard',
    'notifications',
    'accounts_core.apps.AccountsCoreConfig',
    'catalog',
    'sales',
    'purchases',
    'treasury',
    'expenses',
    'reporting',
    'auditlog',
    'api',
    'accounting_bridge.apps.AccountingBridgeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounting_bridge.middleware.AccountingAccessMiddleware',
    'reporting.middleware.ReportDateDefaultsMiddleware',
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ghaith_accounting' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts_core.context_processors.pdf_branding',
                'accounting_bridge.context_processors.app_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# TODO : here i am using a databse like this just for development, for publish use the database that is in the connected server
# NOTE : the previous published version of this code include the 
# settings for the database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Beirut'

# are those needed
USE_I18N = True

USE_TZ = True

# Standard, unambiguous date display across the whole system: day month(name) year
# e.g. "5 Aug 2026" so single-digit months are never confusing.
DATE_FORMAT = "j M Y"
DATETIME_FORMAT = "j M Y, H:i"
SHORT_DATE_FORMAT = "j M Y"
SHORT_DATETIME_FORMAT = "j M Y, H:i"
DATE_INPUT_FORMATS = [
    "%Y-%m-%d",
    "%d/%m/%Y",
    "%d-%m-%Y",
    "%d %b %Y",
    "%d %B %Y",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / 'static_root/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
if 'test' in os.sys.argv:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Browser push (Web Push / VAPID). Generate with: python manage.py generate_vapid_keys --write
def _load_vapid_env():
    vapid_file = BASE_DIR / 'deploy' / 'vapid.env'
    if not vapid_file.exists():
        return
    for line in vapid_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key.strip(), value)


_load_vapid_env()
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:admin@ghaithtravel.com')

# Full site URL for browser push icons (production: https://ghaithtravel.pythonanywhere.com)
CRM_SITE_URL = os.environ.get('CRM_SITE_URL', 'http://127.0.0.1:8000')
CRM_PUSH_ICON_URL = '/static/img/favicon.svg'

# Shared secret for WhatsApp AI dashboard → CRM lead sync API (header: X-API-Key)
EXTERNAL_API_KEY = os.environ.get('EXTERNAL_API_KEY', 'GhaithDashboard-2026-xK9mP2vL7nQ4wR8sT')

# --- Sophia WhatsApp lead-sync integration (hybrid: daily pull + Sold webhook) ---
# Base URL of Sophia's API we pull from (no trailing slash needed).
SOPHIA_BASE_URL = os.environ.get('SOPHIA_BASE_URL', '')
# Bearer token Sophia issues to the CRM for the daily pull (Authorization: Bearer ...).
SOPHIA_API_TOKEN = os.environ.get('SOPHIA_API_TOKEN', '')
# Shared secret the CRM issues to Sophia for the real-time Sold webhook
# (header: X-Webhook-Secret). Provided by the CRM.
SOPHIA_WEBHOOK_SECRET = os.environ.get(
    'SOPHIA_WEBHOOK_SECRET', 'N7XOgeSIflfm9nJROHN0JXohXQglVYrO'
)
# Timeout (seconds) for outbound calls to Sophia.
SOPHIA_HTTP_TIMEOUT = int(os.environ.get('SOPHIA_HTTP_TIMEOUT', '30'))
# On the very first pull (no watermark yet), backfill chats changed since this date.
SOPHIA_BACKFILL_SINCE = os.environ.get('SOPHIA_BACKFILL_SINCE', '2025-01-01T00:00:00+03:00')

# Passcode for Babylon supplier hotel spreadsheet portal (/babylon/)
BABYLON_PORTAL_PASSCODE = os.environ.get('BABYLON_PORTAL_PASSCODE') or 'Babylon-Ghaith-2026'

# Embedded accounting module (Ghaith branding — no Sama references)
COMPANY_LEGAL_NAME = os.environ.get('COMPANY_LEGAL_NAME', 'Ghaith Travel')
COMPANY_ADDRESS = os.environ.get('COMPANY_ADDRESS', 'Bechara El Khoury Highway, Beirut, Lebanon')
COMPANY_PHONE = os.environ.get('COMPANY_PHONE', '+961-81456406')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'info@ghaithtravel.com')
COMPANY_FINANCIAL_ACCOUNT = os.environ.get('COMPANY_FINANCIAL_ACCOUNT', '')
COMPANY_FOOTER_TEXT = os.environ.get('COMPANY_FOOTER_TEXT', '© Ghaith Travel. All rights reserved.')
COMPANY_TAGLINE = os.environ.get('COMPANY_TAGLINE', 'Ghaith Travel & Tourism')
COMPANY_DEFAULT_CURRENCY = os.environ.get('COMPANY_DEFAULT_CURRENCY', 'USD')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Jazzmin admin theme config lives in its own module so dev (system/settings.py)
# and production (ghaithleads/settings.py) share one source of truth. The deploy
# script syncs jazzmin_config.py into the production package automatically.
from .jazzmin_config import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS  # noqa: E402,F401
