# Generated by Django 5.0.6 on 2024-08-26 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='static/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('target_profit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('took_over_leads_today', models.IntegerField(default=0)),
                ('offers_sent', models.TextField(blank=True, null=True)),
                ('offers_sold', models.TextField(blank=True, null=True)),
                ('offers_prepared', models.TextField(blank=True, null=True)),
                ('unqualified_leads', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_travel', models.TextField(blank=True, null=True)),
                ('why_this_destination', models.TextField(blank=True, null=True)),
                ('travel_dates_flexible', models.BooleanField(blank=True, default=False)),
                ('budget_range_from', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_range_to', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='+961', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('channel', models.CharField(max_length=100)),
                ('type_of_service', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('ticket', 'Ticket'), ('visa', 'Visa'), ('package', 'Package'), ('travel insurance', 'Travel Insurance')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('onhold', 'On Hold'), ('processing', 'Processing'), ('negotiation', 'Negotiation'), ('finalized', 'Finalized'), ('followup', 'Follow-Up'), ('done', 'Unqualified')], default='onhold', max_length=50)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('pax', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('travel_date_from', models.DateField(blank=True, null=True)),
                ('travel_date_to', models.DateField(blank=True, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=200)),
                ('profit', models.CharField(blank=True, max_length=200)),
                ('date_notes', models.TextField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('assignment_notes', models.TextField(blank=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('sold', models.BooleanField(blank=True, default=False)),
                ('lost', models.BooleanField(blank=True, default=False)),
                ('finalization_notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('takeover', models.BooleanField(default=True)),
                ('takeover_added_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.PositiveIntegerField(default=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('offer_prepared', models.BooleanField(default=False)),
                ('offer_details', models.TextField(blank=True, null=True)),
                ('moved_to_negotiation', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(blank=True, to='display.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('inclusions', models.TextField()),
                ('exclusions', models.TextField(blank=True)),
                ('itinerary', models.TextField()),
                ('accommodation_options', models.TextField(blank=True)),
                ('flight_details', models.TextField(blank=True)),
                ('pricing_usd', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_created_by', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='display.lead')),
            ],
        ),
        migrations.CreateModel(
            name='UserMonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('target_profit', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
