# Generated by Django 5.0.6 on 2024-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='destination',
            field=models.CharField(blank=True, choices=[('', 'Select Destination')], max_length=200),
        ),
    ]
