# Generated by Django 5.0.6 on 2024-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_alter_lead_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='special_takeover',
            field=models.BooleanField(default=False),
        ),
    ]
