# Generated by Django 5.0.6 on 2024-08-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_lead_special_takeover'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='modified_leads_today',
            field=models.IntegerField(default=0),
        ),
    ]
