# Generated by Django 5.0.6 on 2025-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_dailyreport_modified_leads_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='net',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.CharField(blank=True, choices=[('', 'Select Channel'), ('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Referral', 'Referral'), ('Direct', 'Direct'), ('Website', 'Website'), ('Instagram', 'Instagram')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pax',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type_of_service',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('ticket', 'Ticket'), ('visa', 'Visa'), ('package', 'Package'), ('travel insurance', 'Travel Insurance')], default='', max_length=50),
        ),
    ]
