# Generated by Django 5.0.2 on 2026-04-07 14:55

import display.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_lead_email_crmnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='destination',
            field=models.CharField(blank=True, choices=display.models.get_destination_choices, max_length=200),
        ),
    ]
