# Generated by Django 5.0.2 on 2026-07-02 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_user_crm_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='chat_summary',
            field=models.TextField(blank=True, help_text='AI-generated chat summary synced from the WhatsApp dashboard.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, help_text='Stable ID from the WhatsApp AI dashboard for idempotent sync.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_received_on',
            field=models.CharField(blank=True, help_text='Business WhatsApp line that received the inbound message.', max_length=30),
        ),
        migrations.CreateModel(
            name='CrmUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receives_lead_assignments', models.BooleanField(default=True, help_text='When enabled, this user can receive auto-assigned leads from the dashboard API.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='display.department')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='display.department'),
        ),
    ]
