# Generated by Django 5.0.2 on 2026-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_lead_activity_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SophiaSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('last_pull_at', models.DateTimeField(blank=True, help_text='Watermark: only chats whose status_changed_at is newer are pulled next run.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sophia sync state',
                'verbose_name_plural': 'Sophia sync state',
            },
        ),
        migrations.AddField(
            model_name='crmuserprofile',
            name='sophia_agent_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable Sophia agent id (same id returned by Sophia's /departments and sent as 'assigned_agent' on a chat). Used to map a Sophia agent to this CRM user; the lead's department is then taken from this user's profile.", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last Sophia status_changed_at applied to this lead. The daily pull only applies a chat when its status_changed_at is newer than this (idempotent).', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_agent_action_at',
            field=models.DateTimeField(blank=True, help_text='Last CRM agent action time from the WhatsApp dashboard.', null=True),
        ),
    ]
