# Generated by Django 5.0.6 on 2024-08-26 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('display', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, choices=[('installment', 'Installment'), ('full', 'Full')], max_length=100)),
                ('status', models.CharField(choices=[('onhold', 'On Hold'), ('progress', 'In Progress'), ('done', 'Done')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('travel_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='static/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parentleadtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.leadtask')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leadtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_pay', to='tasks.leadtask')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('net', models.CharField(blank=True, max_length=100)),
                ('selling', models.CharField(blank=True, max_length=100)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('voucher_id', models.CharField(blank=True, max_length=300)),
                ('is_checked', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leadtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.leadtask')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('what_happened', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('onhold', 'On Hold'), ('progress', 'In Progress'), ('done', 'Done')], max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='static/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='tasks.task')),
            ],
        ),
    ]
