# Generated by Django 5.0.6 on 2025-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtask',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtask',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
