# Generated by Django 5.0.2 on 2026-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_leadtask_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtask',
            name='status',
            field=models.CharField(choices=[('onhold', 'On Hold'), ('progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=100),
        ),
    ]
