# Generated by Django 5.0.2 on 2026-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_service_send_to_client_client_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='issue_price',
            field=models.CharField(blank=True, help_text='Actual net at issue date; overrides net when set', max_length=100),
        ),
    ]
