# Generated by Django 5.0.2 on 2026-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_crm_invoice_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Booking Terms & Travel Policy', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Formatted policy text (edited with the rich text editor).')),
                ('show_on_client_invoice', models.BooleanField(default=False, help_text='Append to the client invoice downloaded from edit invoice.', verbose_name='Client invoice PDF')),
                ('show_on_internal_invoice', models.BooleanField(default=False, verbose_name='Internal invoice PDF')),
                ('show_on_purchases_report', models.BooleanField(default=False, verbose_name='Purchases report PDF')),
                ('show_on_client_payments_report', models.BooleanField(default=False, verbose_name='Client payments report PDF')),
                ('show_on_travellers_report', models.BooleanField(default=False, verbose_name='Travellers report PDF')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PDF policy',
                'verbose_name_plural': 'PDF policies',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
