# Generated by Django 5.0.2 on 2026-07-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_leadtask_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabylonHotelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Date the CRM service was created.')),
                ('client_name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, help_text='Net price (maps to service net).', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='babylon_hotel_entry', to='tasks.service')),
            ],
            options={
                'verbose_name': 'Babylon hotel entry',
                'verbose_name_plural': 'Babylon hotel entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
