# Generated by Django 5.0.2 on 2026-07-02 15:33

from django.db import migrations, models


def backfill_service_type(apps, schema_editor):
    BabylonHotelEntry = apps.get_model('tasks', 'BabylonHotelEntry')
    Service = apps.get_model('tasks', 'Service')
    for entry in BabylonHotelEntry.objects.all().iterator():
        service = Service.objects.filter(pk=entry.service_id).first()
        if not service:
            continue
        service_type = (service.service_name or '').strip()
        if service_type and entry.service_type != service_type:
            entry.service_type = service_type
            entry.save(update_fields=['service_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_backfill_babylon_hotel_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='babylonhotelentry',
            name='service_type',
            field=models.CharField(blank=True, help_text='CRM service type (Hotel, Visa, etc.).', max_length=100),
        ),
        migrations.RunPython(backfill_service_type, migrations.RunPython.noop),
    ]
