# Generated by Django 5.0.2 on 2026-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0013_ghaith_company_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default monthly salary in USD; used when preparing payroll rows (not auto-posted).', max_digits=14),
        ),
    ]
