# Generated by Django 5.0.2 on 2026-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_user_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='kind',
            field=models.CharField(choices=[('message', 'New message'), ('lead_assigned', 'Lead assigned to you'), ('leadtask_assigned', 'Order assigned to you'), ('client_payment_due', 'Client payment due'), ('supplier_payment_due', 'Supplier payment due'), ('client_travelling', 'Client travelling'), ('client_return', 'Client return'), ('passport_expiring', 'Passport expiring'), ('media_upload', 'Client media upload'), ('takeover_lead', 'Take over list'), ('broadcast', 'Notice for all')], max_length=40),
        ),
    ]
