# Generated by Django 5.0.2 on 2026-06-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesinvoiceline_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoiceline',
            options={'ordering': ['sort_order', 'id']},
        ),
    ]
