# Generated by Django 5.0.2 on 2026-06-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='notes',
            field=models.TextField(blank=True, help_text='Service details (same as CRM Details column).'),
        ),
    ]
